# Generated by Django 5.1.6 on 2025-02-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(help_text='What is the title of the journal book?', max_length=300)),
                ('purpose', models.CharField(help_text='Describe the purpose of this journal', max_length=300)),
                ('journal_type', models.CharField(help_text='What type of journal (weekly, learning, scientific, etc) is this?', max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('banner_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
