# Generated by Django 5.1.6 on 2025-02-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=models.SlugField(default='pancakes'),
            preserve_default=False,
        ),
    ]
