# Generated by Django 5.1.6 on 2025-02-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
