# Generated by Django 5.1.6 on 2025-02-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journal_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='journal_type',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='start_date',
        ),
    ]
