# Generated by Django 5.1.6 on 2025-02-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journal_banner_image_journal_journal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_title',
            field=models.CharField(help_text='What is the title of the journal book?', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
