# Generated by Django 5.1.6 on 2025-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_journal_journal_title_alter_journal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
