# Generated by Django 5.1.6 on 2025-02-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_journal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='banner_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='journal'),
        ),
    ]
