# Generated by Django 5.1.6 on 2025-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_journal_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='banner_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='journal_banners/'),
        ),
    ]
