# Generated by Django 5.1.6 on 2025-02-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0009_alter_journal_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(help_text="What is the title of today's Journal Entry?", max_length=300)),
                ('todays_date', models.DateField(auto_now_add=True)),
                ('week_entry', models.CharField(help_text='How did your week go? \nWhat successes did you experience?        What did you not achieve this week that you said you will?\n Any magic moments?', max_length=1000)),
                ('learn_entry', models.CharField(help_text='What did I learn              in this week?  About myself?  Others? What do I plan to do                 tomorrow, differently or the same?', max_length=1000)),
                ('interact_entry', models.CharField(help_text='Who did you         interact with?  Anyone you need to update?  Who did you thank? Ask a         question with? Share info or feedback with?', max_length=1000)),
                ('goals_entry', models.CharField(help_text='What are some         goals you have for this next week?', max_length=1000)),
                ('journal_book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
    ]
