# Generated by Django 5.1.6 on 2025-02-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entry',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
