# Generated by Django 5.1.6 on 2025-02-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_journal_banner_image'),
        ('journal_pages', '0002_journal_entry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='journal_book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='journal_book', to='journal.journal'),
        ),
    ]
