# Generated by Django 5.1.6 on 2025-03-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_pages', '0003_alter_journal_entry_journal_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal_entry',
            old_name='todays_date',
            new_name='entry_date',
        ),
    ]
